"""Default actions preselected for each CrewAI Platform application."""

from typing import Final


PLATFORM_APP_DEFAULT_TOOLS: Final[dict[str, tuple[str, str, str]]] = {
    "airtable": ("list_records", "create_records", "get_record"),
    "asana": ("get_projects", "get_workspaces", "get_a_task"),
    "bitbucket": ("create_pull_request", "create_branch", "list_branches"),
    "box": ("create_folder", "save_file_from_object", "list_files"),
    "canva": (
        "post_designs",
        "initiate_canva_design_autofill_job",
        "retrieve_design_autofill_job_status",
    ),
    "clickup": ("create_task", "get_folders", "get_list"),
    "confluence": ("create_page", "search_pages", "get_page_by_id"),
    "daytona": ("create_folder_files", "create_sandbox", "execute_command"),
    "discordbot": (
        "create_message",
        "discordbot_add_group_dm_user",
        "discordbot_add_guild_member",
    ),
    "facebook": ("create_post", "get_page_posts", "create_photo_post"),
    "fathom": ("get_recording_transcript", "list_meetings", "get_recording_summary"),
    "figma": (
        "create_modify_delete_variables",
        "discover_figma_resources",
        "extract_design_tokens",
    ),
    "github": (
        "create_or_update_file_contents",
        "get_repository_content",
        "get_a_tree",
    ),
    "gitlab": ("create_commit", "create_file", "create_merge_request"),
    "gmail": ("send-email", "search-emails", "create_draft"),
    "googleads": (
        "add_or_remove_to_customer_list",
        "create_customer_list",
        "get_campaign_by_id",
    ),
    "google_analytics": ("batch_run_reports", "run_report", "run_realtime_report"),
    "google_calendar": ("create_event", "view_events", "update_event"),
    "google_docs": ("create_document_with_content", "append_text", "create_document"),
    "google_drive": ("download_file", "upload_file", "find_file"),
    "google_maps": ("text_search", "autocomplete", "compute_route_matrix"),
    "google_search_console": ("inspect_url", "list_sites", "search_analytics_query"),
    "google_sheets": ("append_values", "get_values", "update_values"),
    "google_slides": (
        "create_slides_markdown",
        "presentations_batch_update",
        "presentations_get",
    ),
    "googlesuper": ("create_email_draft", "send_email", "fetch_emails"),
    "googletasks": ("update_task_full", "list_all_tasks", "insert_task"),
    "gumroad": ("list_products", "get_sales", "get_user"),
    "hubspot": ("create_contact", "search_contacts", "search_deals"),
    "hugging_face": (
        "generate_chat_completion",
        "generate_embeddings",
        "change_discussions_status",
    ),
    "instagram": ("post_ig_user_media", "post_ig_user_media_publish", "get_user_info"),
    "intercom": (
        "list_conversations",
        "intercom_add_subscription_to_a_contact",
        "intercom_add_tag_to_contact",
    ),
    "jira": ("create_issue", "search_by_jql", "get_projects"),
    "linear": ("search-issues", "update-issue", "run_query_or_mutation"),
    "linkedin": ("create_article_or_url_share", "get_person", "get_post_content"),
    "microsoft_excel": ("update_range_data", "get_worksheets", "create_workbook"),
    "microsoft_onedrive": ("upload_file", "search_files", "create_folder"),
    "microsoft_outlook": ("send_email", "get_message", "get_messages"),
    "microsoft_sharepoint": ("get_drives", "get_sites", "search_files"),
    "microsoft_sharepoint_graph": (
        "add_content_type_column",
        "add_content_type_copy_from_hub",
        "add_content_type_copy_to_list",
    ),
    "microsoft_teams": ("send_message", "get_channels", "get_teams"),
    "microsoft_word": ("create_document", "get_document_content", "get_documents"),
    "monday": ("create_board", "create_column", "create_item"),
    "mural": ("authorization_request", "create_sticky_note", "get_current_user"),
    "notion": ("create_notion_page", "insert_row_database", "search_notion_page"),
    "reddit_ads": ("create_ad_group", "create_campaign", "create_post"),
    "salesforce": ("update_lead", "create_lead", "list_accounts"),
    "slack": ("send-message", "search-messages", "send_direct_message"),
    "slackbot": ("send_message", "find_users", "add_reaction_to_an_item"),
    "square": ("search_orders", "retrieve_order", "search_catalog_objects"),
    "stripe": ("create_customer", "create_subscription", "create_product"),
    "supabase": ("beta_run_sql_query", "run_read_only_query", "get_table_schemas"),
    "todoist": ("create_task", "todoist_add_workspace", "todoist_archive_project2"),
    "trello": ("add_cards", "get_boards_cards_by_id_board", "get_boards_by_id_board"),
    "whatsapp": ("send_message", "register_phone", "upsert_message_template"),
    "youtube": ("upload_video", "update_thumbnail", "multipart_upload_video"),
    "zendesk": (
        "list_zendesk_tickets",
        "search_zendesk",
        "zendesk_apply_zendesk_macro",
    ),
    "zoho_books": (
        "create_expense",
        "create_vendor_payment",
        "zoho_books_accept_estimate",
    ),
    "apaleo": (
        "apaleo_archive_a_property",
        "apaleo_check_if_a_property_exists",
        "apaleo_check_if_a_unit_attribute_exists",
    ),
    "attio": (
        "attio_assert_company",
        "attio_assert_person",
        "attio_assert_user_record",
    ),
    "basecamp": (
        "basecamp_complete_todo",
        "basecamp_create_card",
        "basecamp_create_card_step",
    ),
    "boldsign": (
        "boldsign_brand_get",
        "boldsign_brand_list",
        "boldsign_custom_field_create",
    ),
    "cal": (
        "cal_add_attendee",
        "cal_add_member_to_team_using_org_and_team_id",
        "cal_add_organization_attribute_option",
    ),
    "calendly": (
        "calendly_cancel_scheduled_event",
        "calendly_create_event_type",
        "calendly_create_one_off_event_type",
    ),
    "contentful": (
        "contentful_activate_content_type",
        "contentful_archive_asset",
        "contentful_archive_entry",
    ),
    "dart": (
        "dart_add_task_attachment_from_url",
        "dart_add_task_comment",
        "dart_add_task_time_tracking",
    ),
    "dialpad": (
        "dialpad_access_control_policies_listing",
        "dialpad_add_blocked_phone_numbers",
        "dialpad_add_department_operator_by_id",
    ),
    "digital_ocean": (
        "digital_ocean_create_custom_image",
        "digital_ocean_create_database_cluster",
        "digital_ocean_create_new_block_storage_volume",
    ),
    "discord": (
        "discord_delete_user_application_role_connection",
        "discord_edit_application_command_permissions",
        "discord_get_application_command_permissions",
    ),
    "dropbox": (
        "dropbox_activate_team_folder",
        "dropbox_add_file_member",
        "dropbox_add_file_properties",
    ),
    "dub": ("dub_bulk_delete_links", "dub_bulk_update_links", "dub_create_domain"),
    "dynamics365": (
        "dynamics365_dynamicscrm_create_account",
        "dynamics365_dynamicscrm_create_case",
        "dynamics365_dynamicscrm_create_contact",
    ),
    "eventbrite": (
        "eventbrite_add_ticket_to_group",
        "eventbrite_add_ticket_to_group_by_organization",
        "eventbrite_calculate_price_for_item",
    ),
    "exist": (
        "exist_acquire_attribute_ownership",
        "exist_get_attributes_with_values",
        "exist_get_attribute_templates",
    ),
    "freshbooks": (
        "freshbooks_create_webhook",
        "freshbooks_delete_webhook",
        "freshbooks_get_business_users",
    ),
    "gong": (
        "gong_add_call_media_v2_calls_id_media",
        "gong_add_new_call_v2_calls",
        "gong_aggregate_activity_by_period_via_api",
    ),
    "google_classroom": (
        "google_classroom_courses_aliases_create",
        "google_classroom_courses_aliases_delete",
        "google_classroom_courses_aliases_list",
    ),
    "googlebigquery": (
        "googlebigquery_cancel_job",
        "googlebigquery_create_capacity_commitment",
        "googlebigquery_create_connection",
    ),
    "googlemeet": (
        "googlemeet_create_meet",
        "googlemeet_end_active_conference",
        "googlemeet_get_conference_record_by_name",
    ),
    "googlephotos": (
        "googlephotos_add_enrichment",
        "googlephotos_batch_add_media_items",
        "googlephotos_batch_create_media_items",
    ),
    "gorgias": (
        "gorgias_add_ticket_tags",
        "gorgias_create_account_setting",
        "gorgias_create_customer",
    ),
    "granola_mcp": (
        "granola_mcp_get_account_info",
        "granola_mcp_get_meetings",
        "granola_mcp_get_meeting_transcript",
    ),
    "greenhouse": (
        "greenhouse_activate_user",
        "greenhouse_anonymize_candidate",
        "greenhouse_apply_candidate_tag",
    ),
    "harvest": (
        "harvest_create_client",
        "harvest_create_client_contact",
        "harvest_create_estimate",
    ),
    "kit": (
        "kit_add_subscriber_to_form",
        "kit_add_subscriber_to_form_by_email",
        "kit_create_broadcast",
    ),
    "linkhut": (
        "linkhut_add_bookmark",
        "linkhut_delete_bookmark",
        "linkhut_get_all_tags",
    ),
    "mailchimp": (
        "mailchimp_add_automation",
        "mailchimp_add_batch_webhook",
        "mailchimp_add_campaign",
    ),
    "mercury_mcp": (
        "mercury_mcp_get_account",
        "mercury_mcp_get_account_cards",
        "mercury_mcp_get_accounts",
    ),
    "miro": (
        "miro_attach_tag_to_item",
        "miro_create_app_card_item",
        "miro_create_board",
    ),
    "moneybird": (
        "moneybird_add_note_to_contact",
        "moneybird_archive_contact",
        "moneybird_create_contact",
    ),
    "notebook_lm": (
        "notebook_lm_add_text_sources",
        "notebook_lm_create_audio_overview",
        "notebook_lm_create_notebook",
    ),
    "omnisend": (
        "omnisend_add_cart_product",
        "omnisend_create_batch",
        "omnisend_create_cart",
    ),
    "pagerduty": (
        "pagerduty_add_service_to_incident_workflow_trigger",
        "pagerduty_aggregate_escalation_policy_incident_metrics",
        "pagerduty_aggregate_incident_metrics_with_filters",
    ),
    "pinterest": (
        "pinterest_create_board",
        "pinterest_create_board_section",
        "pinterest_create_pin",
    ),
    "pinterest_ads": (
        "pinterest_ads_get_analytics",
        "pinterest_ads_get_metrics_ready_state",
        "pinterest_ads_get_targeting_options",
    ),
    "prisma": (
        "prisma_create_connection",
        "prisma_create_database",
        "prisma_create_project",
    ),
    "productboard": (
        "productboard_add_note_followers",
        "productboard_add_note_tag",
        "productboard_create_company",
    ),
    "pushbullet": (
        "pushbullet_create_chat",
        "pushbullet_create_device",
        "pushbullet_create_push",
    ),
    "pylon_mcp": (
        "pylon_mcp_create_issue",
        "pylon_mcp_get_account",
        "pylon_mcp_get_contact",
    ),
    "quickbooks": (
        "quickbooks_capture_charge",
        "quickbooks_create_account",
        "quickbooks_create_bank_account",
    ),
    "reddit": (
        "reddit_create_reddit_post",
        "reddit_delete_reddit_comment",
        "reddit_delete_reddit_post",
    ),
    "roam": ("roam_add_group_members", "roam_add_reaction", "roam_create_group"),
    "sentry": (
        "sentry_access_project_information",
        "sentry_add_a_symbol_source_to_a_project",
        "sentry_add_organization_member_via_email",
    ),
    "servicem8": (
        "servicem8_create_job_note",
        "servicem8_create_job_payment",
        "servicem8_create_jobs",
    ),
    "shippo": (
        "shippo_create_address",
        "shippo_create_batch",
        "shippo_create_carrier_account",
    ),
    "shopify": (
        "shopify_add_product_to_custom_collection",
        "shopify_adjust_inventory_level",
        "shopify_apply_fulfillment_hold",
    ),
    "splitwise": (
        "splitwise_add_friend",
        "splitwise_add_user_to_group",
        "splitwise_create_comment",
    ),
    "stack_exchange": (
        "stack_exchange_create_filter",
        "stack_exchange_find_similar_questions",
        "stack_exchange_get_access_tokens",
    ),
    "ticketmaster": (
        "ticketmaster_execute_season_ticketing_command",
        "ticketmaster_get_attraction_details2",
        "ticketmaster_get_attractions",
    ),
    "ticktick": (
        "ticktick_complete_task",
        "ticktick_create_project",
        "ticktick_create_task",
    ),
    "tiktok_ads": (
        "tiktok_ads_appeal_smart_plus_ad",
        "tiktok_ads_assign_tiktok_account_to_advertiser",
        "tiktok_ads_changelog_task_download",
    ),
    "timely": (
        "timely_create_client",
        "timely_create_day_locking",
        "timely_create_label",
    ),
    "toneden": (
        "toneden_create_advertising_campaign",
        "toneden_create_attachment",
        "toneden_create_link",
    ),
    "twitch": (
        "twitch_add_blocked_term",
        "twitch_add_channel_moderator",
        "twitch_add_channel_vip",
    ),
    "typeform": (
        "typeform_create_account_workspace",
        "typeform_create_form",
        "typeform_create_image",
    ),
    "wakatime": (
        "wakatime_get_aggregate_stats",
        "wakatime_get_current_user_status_bar_today",
        "wakatime_get_editors",
    ),
    "wrike": (
        "wrike_bulk_modify_groups",
        "wrike_copy_folder",
        "wrike_copy_folder_async",
    ),
    "yandex": (
        "yandex_geocoder_reverse",
        "yandex_get_account_experiments",
        "yandex_get_account_status",
    ),
    "ynab": (
        "ynab_create_account",
        "ynab_create_scheduled_transaction",
        "ynab_delete_scheduled_transaction",
    ),
    "zeplin": (
        "zeplin_auth_o_auth_authorize",
        "zeplin_connected_components_project_list",
        "zeplin_project_colors_list",
    ),
    "zoho": ("zoho_convert_zoho_lead", "zoho_create_contact", "zoho_create_deal"),
    "zoho_bigin": (
        "zoho_bigin_add_records",
        "zoho_bigin_add_tags_to_records",
        "zoho_bigin_create_bulk_read_job",
    ),
    "zoho_desk": (
        "zoho_desk_create_contact",
        "zoho_desk_create_ticket",
        "zoho_desk_download_ticket_attachment",
    ),
    "zoho_mail": (
        "zoho_mail_accounts_get_signatures",
        "zoho_mail_accounts_list_accounts",
        "zoho_mail_domain_operations",
    ),
    "zoom": (
        "zoom_add_a_meeting_registrant",
        "zoom_add_a_webinar_registrant",
        "zoom_add_project_collaborators",
    ),
    "google_contacts": ("get_contacts", "search_contacts", "list_directory_people"),
    "sap_s4hana": (
        "sap_create_supplier_invoice",
        "sap_get_supplier_invoice_by_id",
        "sap_search_supplier_invoices",
    ),
    "resend": ("add_contact_to_segment", "cancel_email", "create_api_key"),
    "vercel": ("add_environment_variable", "add_project_domain", "assign_alias"),
    "pinecone": ("cancel_bulk_import", "chat_assistant", "chat_completion_assistant"),
}
