# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      patch-minor-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - patch
          - minor
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
