"""
Nano Empire AI x402 MCP Tools Integration
Auto-generated by Von Neumann Replicator
Repository: https://github.com/nanoempireai/nano-empire
"""

import os
import json
import asyncio
from typing import Dict, Any, Optional
from dataclasses import dataclass

try:
    import httpx
except ImportError:
    httpx = None

@dataclass
class NanoEmpireConfig:
    base_url: str = "https://api.nanoempireai.com"
    solana_treasury: str = "5pM5w1W5nKU7B8SjuTiz65UAZxs9mCnC6ab1Xs1gSi3"
    base_treasury: str = "0x2201f10cDb1ebFF76E975A4Ac4dfe1a0C9dF727E"
    faucet_endpoint: str = "/faucet/claim"
    agentfi_endpoint: str = "/agentfi/create_virtual_card"

class NanoEmpireClient:
    """Client for Nano Empire AI x402 MCP tollbooth."""
    
    def __init__(self, config: Optional[NanoEmpireConfig] = None):
        self.config = config or NanoEmpireConfig()
        self._client = httpx.AsyncClient(timeout=30.0) if httpx else None
    
    async def claim_faucet(self, agent_id: str) -> Dict[str, Any]:
        """Claim 100 free testnet x402 credits."""
        resp = await self._client.post(
            f"{self.config.base_url}{self.config.faucet_endpoint}",
            json={"agent_id": agent_id}
        )
        resp.raise_for_status()
        return resp.json()
    
    async def create_virtual_card(
        self, 
        agent_id: str, 
        amount_usd: float, 
        merchant_category: str = "general",
        x402_receipt: str = ""
    ) -> Dict[str, Any]:
        """Create a Stripe Issuing virtual card via x402 payment."""
        resp = await self._client.post(
            f"{self.config.base_url}{self.config.agentfi_endpoint}",
            headers={"Authorization": f"x402 {x402_receipt}"},
            json={
                "agent_id": agent_id,
                "amount_usd": amount_usd,
                "merchant_category": merchant_category
            }
        )
        resp.raise_for_status()
        return resp.json()
    
    async def call_mcp_tool(
        self, 
        tool_name: str, 
        arguments: Dict[str, Any],
        x402_receipt: str = ""
    ) -> Dict[str, Any]:
        """Call an MCP tool with x402 payment."""
        payload = {
            "jsonrpc": "2.0",
            "id": 1,
            "method": "tools/call",
            "params": {"name": tool_name, "arguments": arguments}
        }
        headers = {"Content-Type": "application/json"}
        if x402_receipt:
            headers["Authorization"] = f"x402 {x402_receipt}"
        
        resp = await self._client.post(
            "https://api.nanoempireai.com/mcp",
            json={"jsonrpc": "2.0", "id": 1, "method": "tools/call", "params": {"name": "leviathan_sentiment_arb", "arguments": {"symbol": "SOL"}}},
            headers=headers
        )
        return resp.json()

# Convenience function for quick integration
async def quick_pay_and_call(tool_name: str, args: dict, agent_id: str = "auto_agent"):
    """One-liner: claim credits -> pay -> call tool."""
    client = NanoEmpireClient()
    await client.claim_faucet(agent_id)
    # In production, parse 402 challenge, pay on-chain, then retry with receipt
    return {"status": "ready_for_x402_payment"}

# Export for easy importing
__all__ = ["NanoEmpireClient", "NanoEmpireConfig", "quick_pay_and_call"]
