version: 2.1

jobs:
  build-and-test:
    docker:
      - image: python:3.9.18
    steps:
      - checkout
      - run:
          name: Install poetry
          command: pip install poetry
      - run:
          name: Install dependencies
          command: poetry install
      - run:
          name: Update PATH and Define Environment Variable at Runtime
          command: |
            echo 'export OPENAI_API_KEY=fake-api-key' >> "$BASH_ENV"
            source "$BASH_ENV"
      - run:
          name: Run tests
          command: poetry run pytest

workflows:
  build-and-test:
    jobs:
      - build-and-test