version: 2.1

jobs:
  build-and-test:
    docker:
      - image: python/3.9.18
    steps:
      - checkout
      - install_dependencies:
          command: poetry install
      - run:
          name: Run tests
          command: poetry run pytest

workflows:
  build-and-test:
    jobs:
      - build-and-test