ALGORITHMS = ["RS256"]
WORKOS_DOMAIN = "innovative-soap-49-staging.authkit.app"
WORKOS_CLIENT_ID = "client_01JTK5C207TZBSXQWCVWB1X6HK"
WORKOS_TOKEN_URL = f"https://{WORKOS_DOMAIN}/oauth2/token"
WORKOS_AUTHORIZE_URL = f"https://{WORKOS_DOMAIN}/oauth2/authorize"
WORKOS_ENVIRONMENT_ID = "client_01JNJQWB4HG8T5980R5VHP057C"
