name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Requirements
        run: |
          pip install black

      - name: Run Black
        run: black . --exclude "cli/templates/crew.py" --extend-exclude "cli/templates/main.py"
